services:
  maven:
    build: . 
    container_name: maven-runner   # Name for the container
    working_dir: /app              # Working directory inside the container
    volumes:
      - .:/app                     # Mount current directory to /app inside the container
      - ~/.m2:/root/.m2            # Cache Maven dependencies for faster builds
    command: ["tail", "-f", "/dev/null"]  # Keep the container running
    stdin_open: true               # Keep the container open for interaction
    tty: true                      # Allocate a pseudo-TTY for interactive use
